### ISSUE TITLE
Book Request

### ISSUE THREAD

**Issue by agniji** [changwookjun/StudyBook#3]
Hello,

Would you happen to have the pdf for Deep Learning for Computer Vision with Python: Imagenet Version.
https://www.pyimagesearch.com/deep-learning-computer-vision-python-book/

**Comment by changwookjun** [comment]
Hello
I don't have the book.
I hope you have a good day.

**Comment by JoaoProductDev** [comment]
Hi,

Found it here:
http://93.174.95.29/main/2242000/86aac632847570c96f167cce54cf6490/Adrian%20Rosebrock%20-%20Deep%20Learning%20for%20Computer%20Vision%20with%20Python.%201%2CStarter%20Bundle-PyImageSearch%20%282017%29.pdf

**Comment by agniji** [comment]
That is awesome!
By any chance, could you get hold of the ImageNet version of the same book that came out in 2019?
It has more material and case studies!

Thanks :)
